name: Docker Image CI

on:
  push:
    branches: [ feature/restapi-1 ]
  pull_request:
    branches: [ feature/restapi-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout Code
    - name: Build the Docker image
      run: |
        export TAG=$(date +%s)
        docker build . --file Dockerfile --tag inspirit941/proj-test:$TAG
        docker push inspirit941/proj-test:$TAG
