name: Docker Image CI

on:
  push:
    branches: [ feature/restapi-1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
         cd convert-jenkinsfile
         docker build . --file Dockerfile --tag inspirit941/proj-test:$(date +%s)
