name: Trigger auto deployment for m2ga-backend

on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/m2ga-backend-AutoDeployTrigger-3bd8d988-1f9e-47b2-9f44-b7c317d57ede.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: m2gabackend.azurecr.io
          username: ${{ secrets.M2GABACKEND_REGISTRY_USERNAME }}
          password: ${{ secrets.M2GABACKEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: m2gabackend.azurecr.io/m2ga-backend:${{ github.sha }}
          file: ./Dockerfile
          context: ./
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.M2GABACKEND_AZURE_CREDENTIALS }}
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n m2ga-backend -g m2ga --server m2gabackend.azurecr.io --username  ${{ secrets.M2GABACKEND_REGISTRY_USERNAME }} --password ${{ secrets.M2GABACKEND_REGISTRY_PASSWORD }}
            az containerapp update -n m2ga-backend -g m2ga --image m2gabackend.azurecr.io/m2ga-backend:${{ github.sha }}
